config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root 'home#index'
  get 'home/about'
  root 'friends#index'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends    
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show; end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit; end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: 'Not authorized to edit this friend' if @friend.nil?
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name%>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :last_name%>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email%>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone%>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :twitter%>
    <%= form.text_field :twitter, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  



  

  <div>
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/friends/edit.html.erb
<div class="d-grid gap-3">
  <h1>Editing friend</h1>
  <%= render "form", friend: @friend %>
  <div>
    <%= link_to "Show this friend", @friend, class:"btn btn-dark" %>
    <%= link_to "Back to friends", friends_path, class:"btn btn-dark"%>
  </div>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  
  
  <h1>Friends</h1>
  <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th> First name</th>
        <th> Last name</th>
        <th> Email</th>
        <th> Phone</th>
        <th> Twitter</th>
        <th> Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>
            <td><%= friend.email %></td>
            <td><%= friend.phone %></td>
            <td><%= friend.twitter %></td>
            <td>
              <ul>
                <%= link_to "Show this friend", friend, class:"btn btn-secondary"%>
              </ul>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Add new friend", new_friend_path, class:"btn btn-secondary" %>
<% else %>

 <%= render 'home/index' %>
  
<% end %>
  
  

app/views/friends/new.html.erb
<div class="d-grid gap-3">
  <h1>New friend</h1>
  <%= render "form", friend: @friend %>
  <div><%= link_to "Back to friends", friends_path, class:"btn btn-dark"%></div>
</div>

app/views/friends/show.html.erb
<p>Style 1</p>
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold"> <%= @friend.first_name %> <%= @friend.last_name %> </h1>
    <p class="col-md-8 fs-4"></p>
    <hr>
    <p><%= @friend.email %>  |  <%= @friend.phone %>  |  <%= @friend.twitter %></p>
    <p>
  
      <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary" %>
      <%= link_to "Back to friends", friends_path, class:"btn btn-secondary"  %>
      <%= link_to "Delete Friend", @friend, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-dark' %>
    </p>
    <p>
      
    </p>
  </div>
</div>
<br>
<p>Style 2</p>
<div class="container-fluid bg-dark text-light p-5">
  <div class="container bg-dark p-5">
    <h1 class="display-4"><%= @friend.first_name %>  <%= @friend.last_name %> </h1>
    <hr>
    <p>
      <strong>First nameeeee:</strong>
      <%= @friend.first_name %>
    </p>
    <p>
      <strong>Last name:</strong>
      <%= @friend.last_name %>
    </p>
    <p>
      <strong>Email:</strong>
      <%= @friend.email %>
    </p>
    <p>
      <strong>Phone:</strong>
      <%= @friend.phone %>
    </p>
    <p>
      <strong>Twitter:</strong>
      <%= @friend.twitter %>
    </p>
    <p>
      <%= link_to "Edit friend", edit_friend_path(@friend), class:"btn btn-secondary" %>
      <%= link_to "Back to friends", friends_path, class:"btn btn-secondary"  %>
      <%= link_to "Delete Friend", @friend, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </p>
  </div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark-subtle">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Friends', friends_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Friend', new_friend_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
           <%= link_to 'Sign Out', destroy_user_session_path, class:"nav-link" , data: { turbo_method: :delete } %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/_index.html.erb
<h2>Create an account to access the friends list</h2>

app/views/home/about.html.erb
<h1>about us</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
  <div class="container">
    <%= render 'home/header' %>
    <br>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <%end%>
      <br>
      <%= yield %>
      <br>
    </div>
  </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>